# https://www.reddit.com/r/hyprland/comments/1h4abmt/how_do_i_apply_dark_theme/
# gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
[Settings]
gtk-theme-name = adw-gtk3
gtk-application-prefer-dark-theme = true

