# https://www.reddit.com/r/hyprland/comments/1h4abmt/how_do_i_apply_dark_theme/
# gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
[Settings]
gtk-theme-name = Adwaita:dark
gtk-application-prefer-dark-theme = true
